services:
  - type: web
    name: minervini-screener
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    plan: free
    branch: main
